# Spring Boot configuration
spring:
  application:
    name: rough-copy-spring-boot-rest-api

  # Database properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: ${DB_PASSWORD}

    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true

  #Liquibase properties
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog.yml
    default-schema: liquibase

# Server configuration
server:
  port: 8080 #set your port